version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  backend:
    build:
      context: backend

    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

    volumes:
      - ./backend:/app
    
    ports:
      - "5001:8080"
    
    restart: always

